package com.xujc.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BookExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table info_book
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table info_book
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table info_book
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_book
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public BookExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_book
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_book
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_book
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_book
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_book
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_book
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_book
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_book
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_book
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_book
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table info_book
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBookidIsNull() {
            addCriterion("bookId is null");
            return (Criteria) this;
        }

        public Criteria andBookidIsNotNull() {
            addCriterion("bookId is not null");
            return (Criteria) this;
        }

        public Criteria andBookidEqualTo(String value) {
            addCriterion("bookId =", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidNotEqualTo(String value) {
            addCriterion("bookId <>", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidGreaterThan(String value) {
            addCriterion("bookId >", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidGreaterThanOrEqualTo(String value) {
            addCriterion("bookId >=", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidLessThan(String value) {
            addCriterion("bookId <", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidLessThanOrEqualTo(String value) {
            addCriterion("bookId <=", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidLike(String value) {
            addCriterion("bookId like", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidNotLike(String value) {
            addCriterion("bookId not like", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidIn(List<String> values) {
            addCriterion("bookId in", values, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidNotIn(List<String> values) {
            addCriterion("bookId not in", values, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidBetween(String value1, String value2) {
            addCriterion("bookId between", value1, value2, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidNotBetween(String value1, String value2) {
            addCriterion("bookId not between", value1, value2, "bookid");
            return (Criteria) this;
        }

        public Criteria andBooknameIsNull() {
            addCriterion("bookName is null");
            return (Criteria) this;
        }

        public Criteria andBooknameIsNotNull() {
            addCriterion("bookName is not null");
            return (Criteria) this;
        }

        public Criteria andBooknameEqualTo(String value) {
            addCriterion("bookName =", value, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameNotEqualTo(String value) {
            addCriterion("bookName <>", value, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameGreaterThan(String value) {
            addCriterion("bookName >", value, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameGreaterThanOrEqualTo(String value) {
            addCriterion("bookName >=", value, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameLessThan(String value) {
            addCriterion("bookName <", value, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameLessThanOrEqualTo(String value) {
            addCriterion("bookName <=", value, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameLike(String value) {
            addCriterion("bookName like", value, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameNotLike(String value) {
            addCriterion("bookName not like", value, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameIn(List<String> values) {
            addCriterion("bookName in", values, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameNotIn(List<String> values) {
            addCriterion("bookName not in", values, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameBetween(String value1, String value2) {
            addCriterion("bookName between", value1, value2, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameNotBetween(String value1, String value2) {
            addCriterion("bookName not between", value1, value2, "bookname");
            return (Criteria) this;
        }

        public Criteria andBookeditorIsNull() {
            addCriterion("bookEditor is null");
            return (Criteria) this;
        }

        public Criteria andBookeditorIsNotNull() {
            addCriterion("bookEditor is not null");
            return (Criteria) this;
        }

        public Criteria andBookeditorEqualTo(String value) {
            addCriterion("bookEditor =", value, "bookeditor");
            return (Criteria) this;
        }

        public Criteria andBookeditorNotEqualTo(String value) {
            addCriterion("bookEditor <>", value, "bookeditor");
            return (Criteria) this;
        }

        public Criteria andBookeditorGreaterThan(String value) {
            addCriterion("bookEditor >", value, "bookeditor");
            return (Criteria) this;
        }

        public Criteria andBookeditorGreaterThanOrEqualTo(String value) {
            addCriterion("bookEditor >=", value, "bookeditor");
            return (Criteria) this;
        }

        public Criteria andBookeditorLessThan(String value) {
            addCriterion("bookEditor <", value, "bookeditor");
            return (Criteria) this;
        }

        public Criteria andBookeditorLessThanOrEqualTo(String value) {
            addCriterion("bookEditor <=", value, "bookeditor");
            return (Criteria) this;
        }

        public Criteria andBookeditorLike(String value) {
            addCriterion("bookEditor like", value, "bookeditor");
            return (Criteria) this;
        }

        public Criteria andBookeditorNotLike(String value) {
            addCriterion("bookEditor not like", value, "bookeditor");
            return (Criteria) this;
        }

        public Criteria andBookeditorIn(List<String> values) {
            addCriterion("bookEditor in", values, "bookeditor");
            return (Criteria) this;
        }

        public Criteria andBookeditorNotIn(List<String> values) {
            addCriterion("bookEditor not in", values, "bookeditor");
            return (Criteria) this;
        }

        public Criteria andBookeditorBetween(String value1, String value2) {
            addCriterion("bookEditor between", value1, value2, "bookeditor");
            return (Criteria) this;
        }

        public Criteria andBookeditorNotBetween(String value1, String value2) {
            addCriterion("bookEditor not between", value1, value2, "bookeditor");
            return (Criteria) this;
        }

        public Criteria andBookpressIsNull() {
            addCriterion("bookPress is null");
            return (Criteria) this;
        }

        public Criteria andBookpressIsNotNull() {
            addCriterion("bookPress is not null");
            return (Criteria) this;
        }

        public Criteria andBookpressEqualTo(String value) {
            addCriterion("bookPress =", value, "bookpress");
            return (Criteria) this;
        }

        public Criteria andBookpressNotEqualTo(String value) {
            addCriterion("bookPress <>", value, "bookpress");
            return (Criteria) this;
        }

        public Criteria andBookpressGreaterThan(String value) {
            addCriterion("bookPress >", value, "bookpress");
            return (Criteria) this;
        }

        public Criteria andBookpressGreaterThanOrEqualTo(String value) {
            addCriterion("bookPress >=", value, "bookpress");
            return (Criteria) this;
        }

        public Criteria andBookpressLessThan(String value) {
            addCriterion("bookPress <", value, "bookpress");
            return (Criteria) this;
        }

        public Criteria andBookpressLessThanOrEqualTo(String value) {
            addCriterion("bookPress <=", value, "bookpress");
            return (Criteria) this;
        }

        public Criteria andBookpressLike(String value) {
            addCriterion("bookPress like", value, "bookpress");
            return (Criteria) this;
        }

        public Criteria andBookpressNotLike(String value) {
            addCriterion("bookPress not like", value, "bookpress");
            return (Criteria) this;
        }

        public Criteria andBookpressIn(List<String> values) {
            addCriterion("bookPress in", values, "bookpress");
            return (Criteria) this;
        }

        public Criteria andBookpressNotIn(List<String> values) {
            addCriterion("bookPress not in", values, "bookpress");
            return (Criteria) this;
        }

        public Criteria andBookpressBetween(String value1, String value2) {
            addCriterion("bookPress between", value1, value2, "bookpress");
            return (Criteria) this;
        }

        public Criteria andBookpressNotBetween(String value1, String value2) {
            addCriterion("bookPress not between", value1, value2, "bookpress");
            return (Criteria) this;
        }

        public Criteria andPublicationdateIsNull() {
            addCriterion("publicationDate is null");
            return (Criteria) this;
        }

        public Criteria andPublicationdateIsNotNull() {
            addCriterion("publicationDate is not null");
            return (Criteria) this;
        }

        public Criteria andPublicationdateEqualTo(String value) {
            addCriterion("publicationDate =", value, "publicationdate");
            return (Criteria) this;
        }

        public Criteria andPublicationdateNotEqualTo(String value) {
            addCriterion("publicationDate <>", value, "publicationdate");
            return (Criteria) this;
        }

        public Criteria andPublicationdateGreaterThan(String value) {
            addCriterion("publicationDate >", value, "publicationdate");
            return (Criteria) this;
        }

        public Criteria andPublicationdateGreaterThanOrEqualTo(String value) {
            addCriterion("publicationDate >=", value, "publicationdate");
            return (Criteria) this;
        }

        public Criteria andPublicationdateLessThan(String value) {
            addCriterion("publicationDate <", value, "publicationdate");
            return (Criteria) this;
        }

        public Criteria andPublicationdateLessThanOrEqualTo(String value) {
            addCriterion("publicationDate <=", value, "publicationdate");
            return (Criteria) this;
        }

        public Criteria andPublicationdateLike(String value) {
            addCriterion("publicationDate like", value, "publicationdate");
            return (Criteria) this;
        }

        public Criteria andPublicationdateNotLike(String value) {
            addCriterion("publicationDate not like", value, "publicationdate");
            return (Criteria) this;
        }

        public Criteria andPublicationdateIn(List<String> values) {
            addCriterion("publicationDate in", values, "publicationdate");
            return (Criteria) this;
        }

        public Criteria andPublicationdateNotIn(List<String> values) {
            addCriterion("publicationDate not in", values, "publicationdate");
            return (Criteria) this;
        }

        public Criteria andPublicationdateBetween(String value1, String value2) {
            addCriterion("publicationDate between", value1, value2, "publicationdate");
            return (Criteria) this;
        }

        public Criteria andPublicationdateNotBetween(String value1, String value2) {
            addCriterion("publicationDate not between", value1, value2, "publicationdate");
            return (Criteria) this;
        }

        public Criteria andBookisbnIsNull() {
            addCriterion("bookISBN is null");
            return (Criteria) this;
        }

        public Criteria andBookisbnIsNotNull() {
            addCriterion("bookISBN is not null");
            return (Criteria) this;
        }

        public Criteria andBookisbnEqualTo(String value) {
            addCriterion("bookISBN =", value, "bookisbn");
            return (Criteria) this;
        }

        public Criteria andBookisbnNotEqualTo(String value) {
            addCriterion("bookISBN <>", value, "bookisbn");
            return (Criteria) this;
        }

        public Criteria andBookisbnGreaterThan(String value) {
            addCriterion("bookISBN >", value, "bookisbn");
            return (Criteria) this;
        }

        public Criteria andBookisbnGreaterThanOrEqualTo(String value) {
            addCriterion("bookISBN >=", value, "bookisbn");
            return (Criteria) this;
        }

        public Criteria andBookisbnLessThan(String value) {
            addCriterion("bookISBN <", value, "bookisbn");
            return (Criteria) this;
        }

        public Criteria andBookisbnLessThanOrEqualTo(String value) {
            addCriterion("bookISBN <=", value, "bookisbn");
            return (Criteria) this;
        }

        public Criteria andBookisbnLike(String value) {
            addCriterion("bookISBN like", value, "bookisbn");
            return (Criteria) this;
        }

        public Criteria andBookisbnNotLike(String value) {
            addCriterion("bookISBN not like", value, "bookisbn");
            return (Criteria) this;
        }

        public Criteria andBookisbnIn(List<String> values) {
            addCriterion("bookISBN in", values, "bookisbn");
            return (Criteria) this;
        }

        public Criteria andBookisbnNotIn(List<String> values) {
            addCriterion("bookISBN not in", values, "bookisbn");
            return (Criteria) this;
        }

        public Criteria andBookisbnBetween(String value1, String value2) {
            addCriterion("bookISBN between", value1, value2, "bookisbn");
            return (Criteria) this;
        }

        public Criteria andBookisbnNotBetween(String value1, String value2) {
            addCriterion("bookISBN not between", value1, value2, "bookisbn");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNull() {
            addCriterion("category is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNotNull() {
            addCriterion("category is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryEqualTo(String value) {
            addCriterion("category =", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotEqualTo(String value) {
            addCriterion("category <>", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThan(String value) {
            addCriterion("category >", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("category >=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThan(String value) {
            addCriterion("category <", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThanOrEqualTo(String value) {
            addCriterion("category <=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLike(String value) {
            addCriterion("category like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotLike(String value) {
            addCriterion("category not like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryIn(List<String> values) {
            addCriterion("category in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotIn(List<String> values) {
            addCriterion("category not in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryBetween(String value1, String value2) {
            addCriterion("category between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotBetween(String value1, String value2) {
            addCriterion("category not between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andImgPathIsNull() {
            addCriterion("img_path is null");
            return (Criteria) this;
        }

        public Criteria andImgPathIsNotNull() {
            addCriterion("img_path is not null");
            return (Criteria) this;
        }

        public Criteria andImgPathEqualTo(String value) {
            addCriterion("img_path =", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathNotEqualTo(String value) {
            addCriterion("img_path <>", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathGreaterThan(String value) {
            addCriterion("img_path >", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathGreaterThanOrEqualTo(String value) {
            addCriterion("img_path >=", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathLessThan(String value) {
            addCriterion("img_path <", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathLessThanOrEqualTo(String value) {
            addCriterion("img_path <=", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathLike(String value) {
            addCriterion("img_path like", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathNotLike(String value) {
            addCriterion("img_path not like", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathIn(List<String> values) {
            addCriterion("img_path in", values, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathNotIn(List<String> values) {
            addCriterion("img_path not in", values, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathBetween(String value1, String value2) {
            addCriterion("img_path between", value1, value2, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathNotBetween(String value1, String value2) {
            addCriterion("img_path not between", value1, value2, "imgPath");
            return (Criteria) this;
        }

        public Criteria andInserttimeIsNull() {
            addCriterion("insertTime is null");
            return (Criteria) this;
        }

        public Criteria andInserttimeIsNotNull() {
            addCriterion("insertTime is not null");
            return (Criteria) this;
        }

        public Criteria andInserttimeEqualTo(Date value) {
            addCriterion("insertTime =", value, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeNotEqualTo(Date value) {
            addCriterion("insertTime <>", value, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeGreaterThan(Date value) {
            addCriterion("insertTime >", value, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("insertTime >=", value, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeLessThan(Date value) {
            addCriterion("insertTime <", value, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeLessThanOrEqualTo(Date value) {
            addCriterion("insertTime <=", value, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeIn(List<Date> values) {
            addCriterion("insertTime in", values, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeNotIn(List<Date> values) {
            addCriterion("insertTime not in", values, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeBetween(Date value1, Date value2) {
            addCriterion("insertTime between", value1, value2, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeNotBetween(Date value1, Date value2) {
            addCriterion("insertTime not between", value1, value2, "inserttime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table info_book
     *
     * @mbg.generated do_not_delete_during_merge Sat Dec 30 12:03:56 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table info_book
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}