package com.xujc.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DealExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public DealExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNull() {
            addCriterion("orderId is null");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNotNull() {
            addCriterion("orderId is not null");
            return (Criteria) this;
        }

        public Criteria andOrderidEqualTo(String value) {
            addCriterion("orderId =", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotEqualTo(String value) {
            addCriterion("orderId <>", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThan(String value) {
            addCriterion("orderId >", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThanOrEqualTo(String value) {
            addCriterion("orderId >=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThan(String value) {
            addCriterion("orderId <", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThanOrEqualTo(String value) {
            addCriterion("orderId <=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLike(String value) {
            addCriterion("orderId like", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotLike(String value) {
            addCriterion("orderId not like", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidIn(List<String> values) {
            addCriterion("orderId in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotIn(List<String> values) {
            addCriterion("orderId not in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidBetween(String value1, String value2) {
            addCriterion("orderId between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotBetween(String value1, String value2) {
            addCriterion("orderId not between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andBuyeridIsNull() {
            addCriterion("buyerId is null");
            return (Criteria) this;
        }

        public Criteria andBuyeridIsNotNull() {
            addCriterion("buyerId is not null");
            return (Criteria) this;
        }

        public Criteria andBuyeridEqualTo(String value) {
            addCriterion("buyerId =", value, "buyerid");
            return (Criteria) this;
        }

        public Criteria andBuyeridNotEqualTo(String value) {
            addCriterion("buyerId <>", value, "buyerid");
            return (Criteria) this;
        }

        public Criteria andBuyeridGreaterThan(String value) {
            addCriterion("buyerId >", value, "buyerid");
            return (Criteria) this;
        }

        public Criteria andBuyeridGreaterThanOrEqualTo(String value) {
            addCriterion("buyerId >=", value, "buyerid");
            return (Criteria) this;
        }

        public Criteria andBuyeridLessThan(String value) {
            addCriterion("buyerId <", value, "buyerid");
            return (Criteria) this;
        }

        public Criteria andBuyeridLessThanOrEqualTo(String value) {
            addCriterion("buyerId <=", value, "buyerid");
            return (Criteria) this;
        }

        public Criteria andBuyeridLike(String value) {
            addCriterion("buyerId like", value, "buyerid");
            return (Criteria) this;
        }

        public Criteria andBuyeridNotLike(String value) {
            addCriterion("buyerId not like", value, "buyerid");
            return (Criteria) this;
        }

        public Criteria andBuyeridIn(List<String> values) {
            addCriterion("buyerId in", values, "buyerid");
            return (Criteria) this;
        }

        public Criteria andBuyeridNotIn(List<String> values) {
            addCriterion("buyerId not in", values, "buyerid");
            return (Criteria) this;
        }

        public Criteria andBuyeridBetween(String value1, String value2) {
            addCriterion("buyerId between", value1, value2, "buyerid");
            return (Criteria) this;
        }

        public Criteria andBuyeridNotBetween(String value1, String value2) {
            addCriterion("buyerId not between", value1, value2, "buyerid");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressIsNull() {
            addCriterion("buyerAddress is null");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressIsNotNull() {
            addCriterion("buyerAddress is not null");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressEqualTo(String value) {
            addCriterion("buyerAddress =", value, "buyeraddress");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressNotEqualTo(String value) {
            addCriterion("buyerAddress <>", value, "buyeraddress");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressGreaterThan(String value) {
            addCriterion("buyerAddress >", value, "buyeraddress");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressGreaterThanOrEqualTo(String value) {
            addCriterion("buyerAddress >=", value, "buyeraddress");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressLessThan(String value) {
            addCriterion("buyerAddress <", value, "buyeraddress");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressLessThanOrEqualTo(String value) {
            addCriterion("buyerAddress <=", value, "buyeraddress");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressLike(String value) {
            addCriterion("buyerAddress like", value, "buyeraddress");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressNotLike(String value) {
            addCriterion("buyerAddress not like", value, "buyeraddress");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressIn(List<String> values) {
            addCriterion("buyerAddress in", values, "buyeraddress");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressNotIn(List<String> values) {
            addCriterion("buyerAddress not in", values, "buyeraddress");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressBetween(String value1, String value2) {
            addCriterion("buyerAddress between", value1, value2, "buyeraddress");
            return (Criteria) this;
        }

        public Criteria andBuyeraddressNotBetween(String value1, String value2) {
            addCriterion("buyerAddress not between", value1, value2, "buyeraddress");
            return (Criteria) this;
        }

        public Criteria andDealwayIsNull() {
            addCriterion("dealWay is null");
            return (Criteria) this;
        }

        public Criteria andDealwayIsNotNull() {
            addCriterion("dealWay is not null");
            return (Criteria) this;
        }

        public Criteria andDealwayEqualTo(String value) {
            addCriterion("dealWay =", value, "dealway");
            return (Criteria) this;
        }

        public Criteria andDealwayNotEqualTo(String value) {
            addCriterion("dealWay <>", value, "dealway");
            return (Criteria) this;
        }

        public Criteria andDealwayGreaterThan(String value) {
            addCriterion("dealWay >", value, "dealway");
            return (Criteria) this;
        }

        public Criteria andDealwayGreaterThanOrEqualTo(String value) {
            addCriterion("dealWay >=", value, "dealway");
            return (Criteria) this;
        }

        public Criteria andDealwayLessThan(String value) {
            addCriterion("dealWay <", value, "dealway");
            return (Criteria) this;
        }

        public Criteria andDealwayLessThanOrEqualTo(String value) {
            addCriterion("dealWay <=", value, "dealway");
            return (Criteria) this;
        }

        public Criteria andDealwayLike(String value) {
            addCriterion("dealWay like", value, "dealway");
            return (Criteria) this;
        }

        public Criteria andDealwayNotLike(String value) {
            addCriterion("dealWay not like", value, "dealway");
            return (Criteria) this;
        }

        public Criteria andDealwayIn(List<String> values) {
            addCriterion("dealWay in", values, "dealway");
            return (Criteria) this;
        }

        public Criteria andDealwayNotIn(List<String> values) {
            addCriterion("dealWay not in", values, "dealway");
            return (Criteria) this;
        }

        public Criteria andDealwayBetween(String value1, String value2) {
            addCriterion("dealWay between", value1, value2, "dealway");
            return (Criteria) this;
        }

        public Criteria andDealwayNotBetween(String value1, String value2) {
            addCriterion("dealWay not between", value1, value2, "dealway");
            return (Criteria) this;
        }

        public Criteria andDealpriceIsNull() {
            addCriterion("dealPrice is null");
            return (Criteria) this;
        }

        public Criteria andDealpriceIsNotNull() {
            addCriterion("dealPrice is not null");
            return (Criteria) this;
        }

        public Criteria andDealpriceEqualTo(String value) {
            addCriterion("dealPrice =", value, "dealprice");
            return (Criteria) this;
        }

        public Criteria andDealpriceNotEqualTo(String value) {
            addCriterion("dealPrice <>", value, "dealprice");
            return (Criteria) this;
        }

        public Criteria andDealpriceGreaterThan(String value) {
            addCriterion("dealPrice >", value, "dealprice");
            return (Criteria) this;
        }

        public Criteria andDealpriceGreaterThanOrEqualTo(String value) {
            addCriterion("dealPrice >=", value, "dealprice");
            return (Criteria) this;
        }

        public Criteria andDealpriceLessThan(String value) {
            addCriterion("dealPrice <", value, "dealprice");
            return (Criteria) this;
        }

        public Criteria andDealpriceLessThanOrEqualTo(String value) {
            addCriterion("dealPrice <=", value, "dealprice");
            return (Criteria) this;
        }

        public Criteria andDealpriceLike(String value) {
            addCriterion("dealPrice like", value, "dealprice");
            return (Criteria) this;
        }

        public Criteria andDealpriceNotLike(String value) {
            addCriterion("dealPrice not like", value, "dealprice");
            return (Criteria) this;
        }

        public Criteria andDealpriceIn(List<String> values) {
            addCriterion("dealPrice in", values, "dealprice");
            return (Criteria) this;
        }

        public Criteria andDealpriceNotIn(List<String> values) {
            addCriterion("dealPrice not in", values, "dealprice");
            return (Criteria) this;
        }

        public Criteria andDealpriceBetween(String value1, String value2) {
            addCriterion("dealPrice between", value1, value2, "dealprice");
            return (Criteria) this;
        }

        public Criteria andDealpriceNotBetween(String value1, String value2) {
            addCriterion("dealPrice not between", value1, value2, "dealprice");
            return (Criteria) this;
        }

        public Criteria andNumberIsNull() {
            addCriterion("number is null");
            return (Criteria) this;
        }

        public Criteria andNumberIsNotNull() {
            addCriterion("number is not null");
            return (Criteria) this;
        }

        public Criteria andNumberEqualTo(String value) {
            addCriterion("number =", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotEqualTo(String value) {
            addCriterion("number <>", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThan(String value) {
            addCriterion("number >", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThanOrEqualTo(String value) {
            addCriterion("number >=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThan(String value) {
            addCriterion("number <", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThanOrEqualTo(String value) {
            addCriterion("number <=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLike(String value) {
            addCriterion("number like", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotLike(String value) {
            addCriterion("number not like", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberIn(List<String> values) {
            addCriterion("number in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotIn(List<String> values) {
            addCriterion("number not in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberBetween(String value1, String value2) {
            addCriterion("number between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotBetween(String value1, String value2) {
            addCriterion("number not between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andIspaidIsNull() {
            addCriterion("isPaid is null");
            return (Criteria) this;
        }

        public Criteria andIspaidIsNotNull() {
            addCriterion("isPaid is not null");
            return (Criteria) this;
        }

        public Criteria andIspaidEqualTo(Byte value) {
            addCriterion("isPaid =", value, "ispaid");
            return (Criteria) this;
        }

        public Criteria andIspaidNotEqualTo(Byte value) {
            addCriterion("isPaid <>", value, "ispaid");
            return (Criteria) this;
        }

        public Criteria andIspaidGreaterThan(Byte value) {
            addCriterion("isPaid >", value, "ispaid");
            return (Criteria) this;
        }

        public Criteria andIspaidGreaterThanOrEqualTo(Byte value) {
            addCriterion("isPaid >=", value, "ispaid");
            return (Criteria) this;
        }

        public Criteria andIspaidLessThan(Byte value) {
            addCriterion("isPaid <", value, "ispaid");
            return (Criteria) this;
        }

        public Criteria andIspaidLessThanOrEqualTo(Byte value) {
            addCriterion("isPaid <=", value, "ispaid");
            return (Criteria) this;
        }

        public Criteria andIspaidIn(List<Byte> values) {
            addCriterion("isPaid in", values, "ispaid");
            return (Criteria) this;
        }

        public Criteria andIspaidNotIn(List<Byte> values) {
            addCriterion("isPaid not in", values, "ispaid");
            return (Criteria) this;
        }

        public Criteria andIspaidBetween(Byte value1, Byte value2) {
            addCriterion("isPaid between", value1, value2, "ispaid");
            return (Criteria) this;
        }

        public Criteria andIspaidNotBetween(Byte value1, Byte value2) {
            addCriterion("isPaid not between", value1, value2, "ispaid");
            return (Criteria) this;
        }

        public Criteria andPaidtimeIsNull() {
            addCriterion("paidTime is null");
            return (Criteria) this;
        }

        public Criteria andPaidtimeIsNotNull() {
            addCriterion("paidTime is not null");
            return (Criteria) this;
        }

        public Criteria andPaidtimeEqualTo(Date value) {
            addCriterion("paidTime =", value, "paidtime");
            return (Criteria) this;
        }

        public Criteria andPaidtimeNotEqualTo(Date value) {
            addCriterion("paidTime <>", value, "paidtime");
            return (Criteria) this;
        }

        public Criteria andPaidtimeGreaterThan(Date value) {
            addCriterion("paidTime >", value, "paidtime");
            return (Criteria) this;
        }

        public Criteria andPaidtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("paidTime >=", value, "paidtime");
            return (Criteria) this;
        }

        public Criteria andPaidtimeLessThan(Date value) {
            addCriterion("paidTime <", value, "paidtime");
            return (Criteria) this;
        }

        public Criteria andPaidtimeLessThanOrEqualTo(Date value) {
            addCriterion("paidTime <=", value, "paidtime");
            return (Criteria) this;
        }

        public Criteria andPaidtimeIn(List<Date> values) {
            addCriterion("paidTime in", values, "paidtime");
            return (Criteria) this;
        }

        public Criteria andPaidtimeNotIn(List<Date> values) {
            addCriterion("paidTime not in", values, "paidtime");
            return (Criteria) this;
        }

        public Criteria andPaidtimeBetween(Date value1, Date value2) {
            addCriterion("paidTime between", value1, value2, "paidtime");
            return (Criteria) this;
        }

        public Criteria andPaidtimeNotBetween(Date value1, Date value2) {
            addCriterion("paidTime not between", value1, value2, "paidtime");
            return (Criteria) this;
        }

        public Criteria andInserttimeIsNull() {
            addCriterion("insertTime is null");
            return (Criteria) this;
        }

        public Criteria andInserttimeIsNotNull() {
            addCriterion("insertTime is not null");
            return (Criteria) this;
        }

        public Criteria andInserttimeEqualTo(Date value) {
            addCriterion("insertTime =", value, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeNotEqualTo(Date value) {
            addCriterion("insertTime <>", value, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeGreaterThan(Date value) {
            addCriterion("insertTime >", value, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("insertTime >=", value, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeLessThan(Date value) {
            addCriterion("insertTime <", value, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeLessThanOrEqualTo(Date value) {
            addCriterion("insertTime <=", value, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeIn(List<Date> values) {
            addCriterion("insertTime in", values, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeNotIn(List<Date> values) {
            addCriterion("insertTime not in", values, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeBetween(Date value1, Date value2) {
            addCriterion("insertTime between", value1, value2, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeNotBetween(Date value1, Date value2) {
            addCriterion("insertTime not between", value1, value2, "inserttime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_deal
     *
     * @mbg.generated do_not_delete_during_merge Sat Dec 30 12:03:56 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}