package com.xujc.bean;

import java.util.Date;

public class Electronic {
    public Electronic() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Electronic(Integer id, String bookid, String dllimits, Integer dlcredits, Integer dlnum) {
		super();
		this.id = id;
		this.bookid = bookid;
		this.dllimits = dllimits;
		this.dlcredits = dlcredits;
		this.dlnum = dlnum;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_electronic.id
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private Integer id;
    
    private Book book;

    public Book getBook() {
		return book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_electronic.bookId
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String bookid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_electronic.dlLimits
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String dllimits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_electronic.dlCredits
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private Integer dlcredits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_electronic.dlNum
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private Integer dlnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_electronic.insertTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private Date inserttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_electronic.updateTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_electronic.id
     *
     * @return the value of book_electronic.id
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_electronic.id
     *
     * @param id the value for book_electronic.id
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_electronic.bookId
     *
     * @return the value of book_electronic.bookId
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_electronic.bookId
     *
     * @param bookid the value for book_electronic.bookId
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setBookid(String bookid) {
        this.bookid = bookid == null ? null : bookid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_electronic.dlLimits
     *
     * @return the value of book_electronic.dlLimits
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getDllimits() {
        return dllimits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_electronic.dlLimits
     *
     * @param dllimits the value for book_electronic.dlLimits
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setDllimits(String dllimits) {
        this.dllimits = dllimits == null ? null : dllimits.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_electronic.dlCredits
     *
     * @return the value of book_electronic.dlCredits
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Integer getDlcredits() {
        return dlcredits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_electronic.dlCredits
     *
     * @param dlcredits the value for book_electronic.dlCredits
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setDlcredits(Integer dlcredits) {
        this.dlcredits = dlcredits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_electronic.dlNum
     *
     * @return the value of book_electronic.dlNum
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Integer getDlnum() {
        return dlnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_electronic.dlNum
     *
     * @param dlnum the value for book_electronic.dlNum
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setDlnum(Integer dlnum) {
        this.dlnum = dlnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_electronic.insertTime
     *
     * @return the value of book_electronic.insertTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Date getInserttime() {
        return inserttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_electronic.insertTime
     *
     * @param inserttime the value for book_electronic.insertTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setInserttime(Date inserttime) {
        this.inserttime = inserttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_electronic.updateTime
     *
     * @return the value of book_electronic.updateTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_electronic.updateTime
     *
     * @param updatetime the value for book_electronic.updateTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}