package com.xujc.bean;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_order.id
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_order.orderId
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_order.bookId
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String bookid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_order.sellerId
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String sellerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_order.orderTitle
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String ordertitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_order.orderImage
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String orderimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_order.orderCondition
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String ordercondition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_order.startTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_order.checkTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private Date checktime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_order.finishTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private Date finishtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_order.others
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String others;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_order.insertTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private Date inserttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_order.updateTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_order.id
     *
     * @return the value of info_order.id
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_order.id
     *
     * @param id the value for info_order.id
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_order.orderId
     *
     * @return the value of info_order.orderId
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_order.orderId
     *
     * @param orderid the value for info_order.orderId
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_order.bookId
     *
     * @return the value of info_order.bookId
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_order.bookId
     *
     * @param bookid the value for info_order.bookId
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setBookid(String bookid) {
        this.bookid = bookid == null ? null : bookid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_order.sellerId
     *
     * @return the value of info_order.sellerId
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getSellerid() {
        return sellerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_order.sellerId
     *
     * @param sellerid the value for info_order.sellerId
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setSellerid(String sellerid) {
        this.sellerid = sellerid == null ? null : sellerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_order.orderTitle
     *
     * @return the value of info_order.orderTitle
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getOrdertitle() {
        return ordertitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_order.orderTitle
     *
     * @param ordertitle the value for info_order.orderTitle
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setOrdertitle(String ordertitle) {
        this.ordertitle = ordertitle == null ? null : ordertitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_order.orderImage
     *
     * @return the value of info_order.orderImage
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getOrderimage() {
        return orderimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_order.orderImage
     *
     * @param orderimage the value for info_order.orderImage
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setOrderimage(String orderimage) {
        this.orderimage = orderimage == null ? null : orderimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_order.orderCondition
     *
     * @return the value of info_order.orderCondition
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getOrdercondition() {
        return ordercondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_order.orderCondition
     *
     * @param ordercondition the value for info_order.orderCondition
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setOrdercondition(String ordercondition) {
        this.ordercondition = ordercondition == null ? null : ordercondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_order.startTime
     *
     * @return the value of info_order.startTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_order.startTime
     *
     * @param starttime the value for info_order.startTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_order.checkTime
     *
     * @return the value of info_order.checkTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Date getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_order.checkTime
     *
     * @param checktime the value for info_order.checkTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setChecktime(Date checktime) {
        this.checktime = checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_order.finishTime
     *
     * @return the value of info_order.finishTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Date getFinishtime() {
        return finishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_order.finishTime
     *
     * @param finishtime the value for info_order.finishTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setFinishtime(Date finishtime) {
        this.finishtime = finishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_order.others
     *
     * @return the value of info_order.others
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getOthers() {
        return others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_order.others
     *
     * @param others the value for info_order.others
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setOthers(String others) {
        this.others = others == null ? null : others.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_order.insertTime
     *
     * @return the value of info_order.insertTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Date getInserttime() {
        return inserttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_order.insertTime
     *
     * @param inserttime the value for info_order.insertTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setInserttime(Date inserttime) {
        this.inserttime = inserttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_order.updateTime
     *
     * @return the value of info_order.updateTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_order.updateTime
     *
     * @param updatetime the value for info_order.updateTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}