package com.xujc.bean;

import java.util.Date;

public class Rent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rent.id
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rent.orderId
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rent.buyerId
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String buyerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rent.buyerAddress
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String buyeraddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rent.dealWay
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String dealway;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rent.rental
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String rental;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rent.cashPledge
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String cashpledge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rent.isPaid
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private Byte ispaid;
    
    private String audit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rent.paidTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private Date paidtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rent.insertTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private Date inserttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_rent.updateTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rent.id
     *
     * @return the value of order_rent.id
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rent.id
     *
     * @param id the value for order_rent.id
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rent.orderId
     *
     * @return the value of order_rent.orderId
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rent.orderId
     *
     * @param orderid the value for order_rent.orderId
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rent.buyerId
     *
     * @return the value of order_rent.buyerId
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getBuyerid() {
        return buyerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rent.buyerId
     *
     * @param buyerid the value for order_rent.buyerId
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setBuyerid(String buyerid) {
        this.buyerid = buyerid == null ? null : buyerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rent.buyerAddress
     *
     * @return the value of order_rent.buyerAddress
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getBuyeraddress() {
        return buyeraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rent.buyerAddress
     *
     * @param buyeraddress the value for order_rent.buyerAddress
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setBuyeraddress(String buyeraddress) {
        this.buyeraddress = buyeraddress == null ? null : buyeraddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rent.dealWay
     *
     * @return the value of order_rent.dealWay
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getDealway() {
        return dealway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rent.dealWay
     *
     * @param dealway the value for order_rent.dealWay
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setDealway(String dealway) {
        this.dealway = dealway == null ? null : dealway.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rent.rental
     *
     * @return the value of order_rent.rental
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getRental() {
        return rental;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rent.rental
     *
     * @param rental the value for order_rent.rental
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setRental(String rental) {
        this.rental = rental == null ? null : rental.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rent.cashPledge
     *
     * @return the value of order_rent.cashPledge
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getCashpledge() {
        return cashpledge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rent.cashPledge
     *
     * @param cashpledge the value for order_rent.cashPledge
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setCashpledge(String cashpledge) {
        this.cashpledge = cashpledge == null ? null : cashpledge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rent.isPaid
     *
     * @return the value of order_rent.isPaid
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Byte getIspaid() {
        return ispaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rent.isPaid
     *
     * @param ispaid the value for order_rent.isPaid
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setIspaid(Byte ispaid) {
        this.ispaid = ispaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rent.paidTime
     *
     * @return the value of order_rent.paidTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Date getPaidtime() {
        return paidtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rent.paidTime
     *
     * @param paidtime the value for order_rent.paidTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setPaidtime(Date paidtime) {
        this.paidtime = paidtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rent.insertTime
     *
     * @return the value of order_rent.insertTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Date getInserttime() {
        return inserttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rent.insertTime
     *
     * @param inserttime the value for order_rent.insertTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setInserttime(Date inserttime) {
        this.inserttime = inserttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_rent.updateTime
     *
     * @return the value of order_rent.updateTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_rent.updateTime
     *
     * @param updatetime the value for order_rent.updateTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}