package com.xujc.bean;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable{

    private static final long serialVersionUID = 1L;
	public User() {
		super();
		// TODO Auto-generated constructor stub
	}

	public User(Integer id, String userid, String userpassword, String username, String usergender, String userphone,
			Double userwallet, String userschool, String userdepartment, String usermajor, String stdnumber,
			String useraddress, String useremail) {
		super();
		this.id = id;
		this.userid = userid;
		this.userpassword = userpassword;
		this.username = username;
		this.usergender = usergender;
		this.userphone = userphone;
		this.userwallet = userwallet;
		this.userschool = userschool;
		this.userdepartment = userdepartment;
		this.usermajor = usermajor;
		this.stdnumber = stdnumber;
		this.useraddress = useraddress;
		this.useremail = useremail;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.id
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.userId
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.userPassword
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String userpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.userName
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.userGender
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String usergender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.userPhone
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String userphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.userWallet
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private Double userwallet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.userSchool
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String userschool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.userDepartment
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String userdepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.userMajor
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String usermajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.stdNumber
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String stdnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.userAddress
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String useraddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.userEmail
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private String useremail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.insertTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private Date inserttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.updateTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.id
     *
     * @return the value of info_user.id
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.id
     *
     * @param id the value for info_user.id
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.userId
     *
     * @return the value of info_user.userId
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.userId
     *
     * @param userid the value for info_user.userId
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.userPassword
     *
     * @return the value of info_user.userPassword
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getUserpassword() {
        return userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.userPassword
     *
     * @param userpassword the value for info_user.userPassword
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword == null ? null : userpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.userName
     *
     * @return the value of info_user.userName
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.userName
     *
     * @param username the value for info_user.userName
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.userGender
     *
     * @return the value of info_user.userGender
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getUsergender() {
        return usergender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.userGender
     *
     * @param usergender the value for info_user.userGender
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setUsergender(String usergender) {
        this.usergender = usergender == null ? null : usergender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.userPhone
     *
     * @return the value of info_user.userPhone
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getUserphone() {
        return userphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.userPhone
     *
     * @param userphone the value for info_user.userPhone
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setUserphone(String userphone) {
        this.userphone = userphone == null ? null : userphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.userWallet
     *
     * @return the value of info_user.userWallet
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Double getUserwallet() {
        return userwallet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.userWallet
     *
     * @param userwallet the value for info_user.userWallet
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setUserwallet(Double userwallet) {
        this.userwallet = userwallet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.userSchool
     *
     * @return the value of info_user.userSchool
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getUserschool() {
        return userschool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.userSchool
     *
     * @param userschool the value for info_user.userSchool
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setUserschool(String userschool) {
        this.userschool = userschool == null ? null : userschool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.userDepartment
     *
     * @return the value of info_user.userDepartment
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getUserdepartment() {
        return userdepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.userDepartment
     *
     * @param userdepartment the value for info_user.userDepartment
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setUserdepartment(String userdepartment) {
        this.userdepartment = userdepartment == null ? null : userdepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.userMajor
     *
     * @return the value of info_user.userMajor
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getUsermajor() {
        return usermajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.userMajor
     *
     * @param usermajor the value for info_user.userMajor
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setUsermajor(String usermajor) {
        this.usermajor = usermajor == null ? null : usermajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.stdNumber
     *
     * @return the value of info_user.stdNumber
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getStdnumber() {
        return stdnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.stdNumber
     *
     * @param stdnumber the value for info_user.stdNumber
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setStdnumber(String stdnumber) {
        this.stdnumber = stdnumber == null ? null : stdnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.userAddress
     *
     * @return the value of info_user.userAddress
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getUseraddress() {
        return useraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.userAddress
     *
     * @param useraddress the value for info_user.userAddress
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setUseraddress(String useraddress) {
        this.useraddress = useraddress == null ? null : useraddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.userEmail
     *
     * @return the value of info_user.userEmail
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getUseremail() {
        return useremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.userEmail
     *
     * @param useremail the value for info_user.userEmail
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setUseremail(String useremail) {
        this.useremail = useremail == null ? null : useremail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.insertTime
     *
     * @return the value of info_user.insertTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Date getInserttime() {
        return inserttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.insertTime
     *
     * @param inserttime the value for info_user.insertTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setInserttime(Date inserttime) {
        this.inserttime = inserttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.updateTime
     *
     * @return the value of info_user.updateTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.updateTime
     *
     * @param updatetime the value for info_user.updateTime
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}