package com.xujc.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("userId =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("userId <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("userId >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("userId >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("userId <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("userId <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("userId like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("userId not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("userId in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("userId not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("userId between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("userId not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUserpasswordIsNull() {
            addCriterion("userPassword is null");
            return (Criteria) this;
        }

        public Criteria andUserpasswordIsNotNull() {
            addCriterion("userPassword is not null");
            return (Criteria) this;
        }

        public Criteria andUserpasswordEqualTo(String value) {
            addCriterion("userPassword =", value, "userpassword");
            return (Criteria) this;
        }

        public Criteria andUserpasswordNotEqualTo(String value) {
            addCriterion("userPassword <>", value, "userpassword");
            return (Criteria) this;
        }

        public Criteria andUserpasswordGreaterThan(String value) {
            addCriterion("userPassword >", value, "userpassword");
            return (Criteria) this;
        }

        public Criteria andUserpasswordGreaterThanOrEqualTo(String value) {
            addCriterion("userPassword >=", value, "userpassword");
            return (Criteria) this;
        }

        public Criteria andUserpasswordLessThan(String value) {
            addCriterion("userPassword <", value, "userpassword");
            return (Criteria) this;
        }

        public Criteria andUserpasswordLessThanOrEqualTo(String value) {
            addCriterion("userPassword <=", value, "userpassword");
            return (Criteria) this;
        }

        public Criteria andUserpasswordLike(String value) {
            addCriterion("userPassword like", value, "userpassword");
            return (Criteria) this;
        }

        public Criteria andUserpasswordNotLike(String value) {
            addCriterion("userPassword not like", value, "userpassword");
            return (Criteria) this;
        }

        public Criteria andUserpasswordIn(List<String> values) {
            addCriterion("userPassword in", values, "userpassword");
            return (Criteria) this;
        }

        public Criteria andUserpasswordNotIn(List<String> values) {
            addCriterion("userPassword not in", values, "userpassword");
            return (Criteria) this;
        }

        public Criteria andUserpasswordBetween(String value1, String value2) {
            addCriterion("userPassword between", value1, value2, "userpassword");
            return (Criteria) this;
        }

        public Criteria andUserpasswordNotBetween(String value1, String value2) {
            addCriterion("userPassword not between", value1, value2, "userpassword");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("userName is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("userName is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("userName =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("userName <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("userName >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("userName >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("userName <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("userName <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("userName like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("userName not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("userName in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("userName not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("userName between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("userName not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsergenderIsNull() {
            addCriterion("userGender is null");
            return (Criteria) this;
        }

        public Criteria andUsergenderIsNotNull() {
            addCriterion("userGender is not null");
            return (Criteria) this;
        }

        public Criteria andUsergenderEqualTo(String value) {
            addCriterion("userGender =", value, "usergender");
            return (Criteria) this;
        }

        public Criteria andUsergenderNotEqualTo(String value) {
            addCriterion("userGender <>", value, "usergender");
            return (Criteria) this;
        }

        public Criteria andUsergenderGreaterThan(String value) {
            addCriterion("userGender >", value, "usergender");
            return (Criteria) this;
        }

        public Criteria andUsergenderGreaterThanOrEqualTo(String value) {
            addCriterion("userGender >=", value, "usergender");
            return (Criteria) this;
        }

        public Criteria andUsergenderLessThan(String value) {
            addCriterion("userGender <", value, "usergender");
            return (Criteria) this;
        }

        public Criteria andUsergenderLessThanOrEqualTo(String value) {
            addCriterion("userGender <=", value, "usergender");
            return (Criteria) this;
        }

        public Criteria andUsergenderLike(String value) {
            addCriterion("userGender like", value, "usergender");
            return (Criteria) this;
        }

        public Criteria andUsergenderNotLike(String value) {
            addCriterion("userGender not like", value, "usergender");
            return (Criteria) this;
        }

        public Criteria andUsergenderIn(List<String> values) {
            addCriterion("userGender in", values, "usergender");
            return (Criteria) this;
        }

        public Criteria andUsergenderNotIn(List<String> values) {
            addCriterion("userGender not in", values, "usergender");
            return (Criteria) this;
        }

        public Criteria andUsergenderBetween(String value1, String value2) {
            addCriterion("userGender between", value1, value2, "usergender");
            return (Criteria) this;
        }

        public Criteria andUsergenderNotBetween(String value1, String value2) {
            addCriterion("userGender not between", value1, value2, "usergender");
            return (Criteria) this;
        }

        public Criteria andUserphoneIsNull() {
            addCriterion("userPhone is null");
            return (Criteria) this;
        }

        public Criteria andUserphoneIsNotNull() {
            addCriterion("userPhone is not null");
            return (Criteria) this;
        }

        public Criteria andUserphoneEqualTo(String value) {
            addCriterion("userPhone =", value, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneNotEqualTo(String value) {
            addCriterion("userPhone <>", value, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneGreaterThan(String value) {
            addCriterion("userPhone >", value, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneGreaterThanOrEqualTo(String value) {
            addCriterion("userPhone >=", value, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneLessThan(String value) {
            addCriterion("userPhone <", value, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneLessThanOrEqualTo(String value) {
            addCriterion("userPhone <=", value, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneLike(String value) {
            addCriterion("userPhone like", value, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneNotLike(String value) {
            addCriterion("userPhone not like", value, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneIn(List<String> values) {
            addCriterion("userPhone in", values, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneNotIn(List<String> values) {
            addCriterion("userPhone not in", values, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneBetween(String value1, String value2) {
            addCriterion("userPhone between", value1, value2, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneNotBetween(String value1, String value2) {
            addCriterion("userPhone not between", value1, value2, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserwalletIsNull() {
            addCriterion("userWallet is null");
            return (Criteria) this;
        }

        public Criteria andUserwalletIsNotNull() {
            addCriterion("userWallet is not null");
            return (Criteria) this;
        }

        public Criteria andUserwalletEqualTo(Double value) {
            addCriterion("userWallet =", value, "userwallet");
            return (Criteria) this;
        }

        public Criteria andUserwalletNotEqualTo(Double value) {
            addCriterion("userWallet <>", value, "userwallet");
            return (Criteria) this;
        }

        public Criteria andUserwalletGreaterThan(Double value) {
            addCriterion("userWallet >", value, "userwallet");
            return (Criteria) this;
        }

        public Criteria andUserwalletGreaterThanOrEqualTo(Double value) {
            addCriterion("userWallet >=", value, "userwallet");
            return (Criteria) this;
        }

        public Criteria andUserwalletLessThan(Double value) {
            addCriterion("userWallet <", value, "userwallet");
            return (Criteria) this;
        }

        public Criteria andUserwalletLessThanOrEqualTo(Double value) {
            addCriterion("userWallet <=", value, "userwallet");
            return (Criteria) this;
        }

        public Criteria andUserwalletIn(List<Double> values) {
            addCriterion("userWallet in", values, "userwallet");
            return (Criteria) this;
        }

        public Criteria andUserwalletNotIn(List<Double> values) {
            addCriterion("userWallet not in", values, "userwallet");
            return (Criteria) this;
        }

        public Criteria andUserwalletBetween(Double value1, Double value2) {
            addCriterion("userWallet between", value1, value2, "userwallet");
            return (Criteria) this;
        }

        public Criteria andUserwalletNotBetween(Double value1, Double value2) {
            addCriterion("userWallet not between", value1, value2, "userwallet");
            return (Criteria) this;
        }

        public Criteria andUserschoolIsNull() {
            addCriterion("userSchool is null");
            return (Criteria) this;
        }

        public Criteria andUserschoolIsNotNull() {
            addCriterion("userSchool is not null");
            return (Criteria) this;
        }

        public Criteria andUserschoolEqualTo(String value) {
            addCriterion("userSchool =", value, "userschool");
            return (Criteria) this;
        }

        public Criteria andUserschoolNotEqualTo(String value) {
            addCriterion("userSchool <>", value, "userschool");
            return (Criteria) this;
        }

        public Criteria andUserschoolGreaterThan(String value) {
            addCriterion("userSchool >", value, "userschool");
            return (Criteria) this;
        }

        public Criteria andUserschoolGreaterThanOrEqualTo(String value) {
            addCriterion("userSchool >=", value, "userschool");
            return (Criteria) this;
        }

        public Criteria andUserschoolLessThan(String value) {
            addCriterion("userSchool <", value, "userschool");
            return (Criteria) this;
        }

        public Criteria andUserschoolLessThanOrEqualTo(String value) {
            addCriterion("userSchool <=", value, "userschool");
            return (Criteria) this;
        }

        public Criteria andUserschoolLike(String value) {
            addCriterion("userSchool like", value, "userschool");
            return (Criteria) this;
        }

        public Criteria andUserschoolNotLike(String value) {
            addCriterion("userSchool not like", value, "userschool");
            return (Criteria) this;
        }

        public Criteria andUserschoolIn(List<String> values) {
            addCriterion("userSchool in", values, "userschool");
            return (Criteria) this;
        }

        public Criteria andUserschoolNotIn(List<String> values) {
            addCriterion("userSchool not in", values, "userschool");
            return (Criteria) this;
        }

        public Criteria andUserschoolBetween(String value1, String value2) {
            addCriterion("userSchool between", value1, value2, "userschool");
            return (Criteria) this;
        }

        public Criteria andUserschoolNotBetween(String value1, String value2) {
            addCriterion("userSchool not between", value1, value2, "userschool");
            return (Criteria) this;
        }

        public Criteria andUserdepartmentIsNull() {
            addCriterion("userDepartment is null");
            return (Criteria) this;
        }

        public Criteria andUserdepartmentIsNotNull() {
            addCriterion("userDepartment is not null");
            return (Criteria) this;
        }

        public Criteria andUserdepartmentEqualTo(String value) {
            addCriterion("userDepartment =", value, "userdepartment");
            return (Criteria) this;
        }

        public Criteria andUserdepartmentNotEqualTo(String value) {
            addCriterion("userDepartment <>", value, "userdepartment");
            return (Criteria) this;
        }

        public Criteria andUserdepartmentGreaterThan(String value) {
            addCriterion("userDepartment >", value, "userdepartment");
            return (Criteria) this;
        }

        public Criteria andUserdepartmentGreaterThanOrEqualTo(String value) {
            addCriterion("userDepartment >=", value, "userdepartment");
            return (Criteria) this;
        }

        public Criteria andUserdepartmentLessThan(String value) {
            addCriterion("userDepartment <", value, "userdepartment");
            return (Criteria) this;
        }

        public Criteria andUserdepartmentLessThanOrEqualTo(String value) {
            addCriterion("userDepartment <=", value, "userdepartment");
            return (Criteria) this;
        }

        public Criteria andUserdepartmentLike(String value) {
            addCriterion("userDepartment like", value, "userdepartment");
            return (Criteria) this;
        }

        public Criteria andUserdepartmentNotLike(String value) {
            addCriterion("userDepartment not like", value, "userdepartment");
            return (Criteria) this;
        }

        public Criteria andUserdepartmentIn(List<String> values) {
            addCriterion("userDepartment in", values, "userdepartment");
            return (Criteria) this;
        }

        public Criteria andUserdepartmentNotIn(List<String> values) {
            addCriterion("userDepartment not in", values, "userdepartment");
            return (Criteria) this;
        }

        public Criteria andUserdepartmentBetween(String value1, String value2) {
            addCriterion("userDepartment between", value1, value2, "userdepartment");
            return (Criteria) this;
        }

        public Criteria andUserdepartmentNotBetween(String value1, String value2) {
            addCriterion("userDepartment not between", value1, value2, "userdepartment");
            return (Criteria) this;
        }

        public Criteria andUsermajorIsNull() {
            addCriterion("userMajor is null");
            return (Criteria) this;
        }

        public Criteria andUsermajorIsNotNull() {
            addCriterion("userMajor is not null");
            return (Criteria) this;
        }

        public Criteria andUsermajorEqualTo(String value) {
            addCriterion("userMajor =", value, "usermajor");
            return (Criteria) this;
        }

        public Criteria andUsermajorNotEqualTo(String value) {
            addCriterion("userMajor <>", value, "usermajor");
            return (Criteria) this;
        }

        public Criteria andUsermajorGreaterThan(String value) {
            addCriterion("userMajor >", value, "usermajor");
            return (Criteria) this;
        }

        public Criteria andUsermajorGreaterThanOrEqualTo(String value) {
            addCriterion("userMajor >=", value, "usermajor");
            return (Criteria) this;
        }

        public Criteria andUsermajorLessThan(String value) {
            addCriterion("userMajor <", value, "usermajor");
            return (Criteria) this;
        }

        public Criteria andUsermajorLessThanOrEqualTo(String value) {
            addCriterion("userMajor <=", value, "usermajor");
            return (Criteria) this;
        }

        public Criteria andUsermajorLike(String value) {
            addCriterion("userMajor like", value, "usermajor");
            return (Criteria) this;
        }

        public Criteria andUsermajorNotLike(String value) {
            addCriterion("userMajor not like", value, "usermajor");
            return (Criteria) this;
        }

        public Criteria andUsermajorIn(List<String> values) {
            addCriterion("userMajor in", values, "usermajor");
            return (Criteria) this;
        }

        public Criteria andUsermajorNotIn(List<String> values) {
            addCriterion("userMajor not in", values, "usermajor");
            return (Criteria) this;
        }

        public Criteria andUsermajorBetween(String value1, String value2) {
            addCriterion("userMajor between", value1, value2, "usermajor");
            return (Criteria) this;
        }

        public Criteria andUsermajorNotBetween(String value1, String value2) {
            addCriterion("userMajor not between", value1, value2, "usermajor");
            return (Criteria) this;
        }

        public Criteria andStdnumberIsNull() {
            addCriterion("stdNumber is null");
            return (Criteria) this;
        }

        public Criteria andStdnumberIsNotNull() {
            addCriterion("stdNumber is not null");
            return (Criteria) this;
        }

        public Criteria andStdnumberEqualTo(String value) {
            addCriterion("stdNumber =", value, "stdnumber");
            return (Criteria) this;
        }

        public Criteria andStdnumberNotEqualTo(String value) {
            addCriterion("stdNumber <>", value, "stdnumber");
            return (Criteria) this;
        }

        public Criteria andStdnumberGreaterThan(String value) {
            addCriterion("stdNumber >", value, "stdnumber");
            return (Criteria) this;
        }

        public Criteria andStdnumberGreaterThanOrEqualTo(String value) {
            addCriterion("stdNumber >=", value, "stdnumber");
            return (Criteria) this;
        }

        public Criteria andStdnumberLessThan(String value) {
            addCriterion("stdNumber <", value, "stdnumber");
            return (Criteria) this;
        }

        public Criteria andStdnumberLessThanOrEqualTo(String value) {
            addCriterion("stdNumber <=", value, "stdnumber");
            return (Criteria) this;
        }

        public Criteria andStdnumberLike(String value) {
            addCriterion("stdNumber like", value, "stdnumber");
            return (Criteria) this;
        }

        public Criteria andStdnumberNotLike(String value) {
            addCriterion("stdNumber not like", value, "stdnumber");
            return (Criteria) this;
        }

        public Criteria andStdnumberIn(List<String> values) {
            addCriterion("stdNumber in", values, "stdnumber");
            return (Criteria) this;
        }

        public Criteria andStdnumberNotIn(List<String> values) {
            addCriterion("stdNumber not in", values, "stdnumber");
            return (Criteria) this;
        }

        public Criteria andStdnumberBetween(String value1, String value2) {
            addCriterion("stdNumber between", value1, value2, "stdnumber");
            return (Criteria) this;
        }

        public Criteria andStdnumberNotBetween(String value1, String value2) {
            addCriterion("stdNumber not between", value1, value2, "stdnumber");
            return (Criteria) this;
        }

        public Criteria andUseraddressIsNull() {
            addCriterion("userAddress is null");
            return (Criteria) this;
        }

        public Criteria andUseraddressIsNotNull() {
            addCriterion("userAddress is not null");
            return (Criteria) this;
        }

        public Criteria andUseraddressEqualTo(String value) {
            addCriterion("userAddress =", value, "useraddress");
            return (Criteria) this;
        }

        public Criteria andUseraddressNotEqualTo(String value) {
            addCriterion("userAddress <>", value, "useraddress");
            return (Criteria) this;
        }

        public Criteria andUseraddressGreaterThan(String value) {
            addCriterion("userAddress >", value, "useraddress");
            return (Criteria) this;
        }

        public Criteria andUseraddressGreaterThanOrEqualTo(String value) {
            addCriterion("userAddress >=", value, "useraddress");
            return (Criteria) this;
        }

        public Criteria andUseraddressLessThan(String value) {
            addCriterion("userAddress <", value, "useraddress");
            return (Criteria) this;
        }

        public Criteria andUseraddressLessThanOrEqualTo(String value) {
            addCriterion("userAddress <=", value, "useraddress");
            return (Criteria) this;
        }

        public Criteria andUseraddressLike(String value) {
            addCriterion("userAddress like", value, "useraddress");
            return (Criteria) this;
        }

        public Criteria andUseraddressNotLike(String value) {
            addCriterion("userAddress not like", value, "useraddress");
            return (Criteria) this;
        }

        public Criteria andUseraddressIn(List<String> values) {
            addCriterion("userAddress in", values, "useraddress");
            return (Criteria) this;
        }

        public Criteria andUseraddressNotIn(List<String> values) {
            addCriterion("userAddress not in", values, "useraddress");
            return (Criteria) this;
        }

        public Criteria andUseraddressBetween(String value1, String value2) {
            addCriterion("userAddress between", value1, value2, "useraddress");
            return (Criteria) this;
        }

        public Criteria andUseraddressNotBetween(String value1, String value2) {
            addCriterion("userAddress not between", value1, value2, "useraddress");
            return (Criteria) this;
        }

        public Criteria andUseremailIsNull() {
            addCriterion("userEmail is null");
            return (Criteria) this;
        }

        public Criteria andUseremailIsNotNull() {
            addCriterion("userEmail is not null");
            return (Criteria) this;
        }

        public Criteria andUseremailEqualTo(String value) {
            addCriterion("userEmail =", value, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailNotEqualTo(String value) {
            addCriterion("userEmail <>", value, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailGreaterThan(String value) {
            addCriterion("userEmail >", value, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailGreaterThanOrEqualTo(String value) {
            addCriterion("userEmail >=", value, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailLessThan(String value) {
            addCriterion("userEmail <", value, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailLessThanOrEqualTo(String value) {
            addCriterion("userEmail <=", value, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailLike(String value) {
            addCriterion("userEmail like", value, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailNotLike(String value) {
            addCriterion("userEmail not like", value, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailIn(List<String> values) {
            addCriterion("userEmail in", values, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailNotIn(List<String> values) {
            addCriterion("userEmail not in", values, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailBetween(String value1, String value2) {
            addCriterion("userEmail between", value1, value2, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailNotBetween(String value1, String value2) {
            addCriterion("userEmail not between", value1, value2, "useremail");
            return (Criteria) this;
        }

        public Criteria andInserttimeIsNull() {
            addCriterion("insertTime is null");
            return (Criteria) this;
        }

        public Criteria andInserttimeIsNotNull() {
            addCriterion("insertTime is not null");
            return (Criteria) this;
        }

        public Criteria andInserttimeEqualTo(Date value) {
            addCriterion("insertTime =", value, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeNotEqualTo(Date value) {
            addCriterion("insertTime <>", value, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeGreaterThan(Date value) {
            addCriterion("insertTime >", value, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("insertTime >=", value, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeLessThan(Date value) {
            addCriterion("insertTime <", value, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeLessThanOrEqualTo(Date value) {
            addCriterion("insertTime <=", value, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeIn(List<Date> values) {
            addCriterion("insertTime in", values, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeNotIn(List<Date> values) {
            addCriterion("insertTime not in", values, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeBetween(Date value1, Date value2) {
            addCriterion("insertTime between", value1, value2, "inserttime");
            return (Criteria) this;
        }

        public Criteria andInserttimeNotBetween(Date value1, Date value2) {
            addCriterion("insertTime not between", value1, value2, "inserttime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table info_user
     *
     * @mbg.generated do_not_delete_during_merge Sat Dec 30 12:03:56 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}