package com.xujc.dao;

import com.xujc.bean.Deal;
import com.xujc.bean.DealExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DealMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    long countByExample(DealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    int deleteByExample(DealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    int insert(Deal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    int insertSelective(Deal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    List<Deal> selectByExample(DealExample example);
    
    List<Deal> selectByPrimaryKeywithOrder();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    Deal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    int updateByExampleSelective(@Param("record") Deal record, @Param("example") DealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    int updateByExample(@Param("record") Deal record, @Param("example") DealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    int updateByPrimaryKeySelective(Deal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_deal
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    int updateByPrimaryKey(Deal record);
}