package com.xujc.dao;

import com.xujc.bean.Paper;
import com.xujc.bean.PaperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_paper
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    long countByExample(PaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_paper
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    int deleteByExample(PaperExample example);

    int deleteBathById(List<String> list);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_paper
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_paper
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    int insert(Paper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_paper
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    int insertSelective(Paper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_paper
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    List<Paper> selectByExample(PaperExample example);

    List<Paper> selectByPrimaryKeywithbook();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_paper
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    Paper selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_paper
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    int updateByExampleSelective(@Param("record") Paper record, @Param("example") PaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_paper
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    int updateByExample(@Param("record") Paper record, @Param("example") PaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_paper
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    int updateByPrimaryKeySelective(Paper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_paper
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    int updateByPrimaryKey(Paper record);
}