package com.xujc.dao;

import com.xujc.bean.User;
import com.xujc.bean.UserExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    int deleteByExample(UserExample example);
    
    int deleteBathById(List<String> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    int insert(User record);
    
    int insertApi(String keys,String values);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    List<User> selectByExample(UserExample example);

    List<Map<String,Object>> selectApi(String selector,String tablename,String condition,String group,String order);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Sat Dec 30 12:03:56 CST 2017
     */
    int updateByPrimaryKey(User record);
}